build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank account"
  contactDetails:
    name: "Shubham PROD"
    email: "shubham@prod"
  onCallSupport:
    - (333)333-1234
    - (333)333-5678