build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank account"
  contactDetails:
    name: "Shubham Dev"
    email: "shubham@dev"
  onCallSupport:
    - (111)111-1234
    - (111)111-5678





