spring:
  application:
    name: "configserver"
  profiles:
    active: native # tell to activate native profile of spring cloud config server
  cloud:
    config:
      server:
        native:
          #search-location: "classpath:/config"
          search-locations: "file:///F://Learn CS//Microservices//myMS//config"

server:
  port: 8071