spring:
  application:
    name: "configserver"
  profiles:
    #active: native # tell to activate native profile of spring cloud config server
    #native is used onl with classpath loaction or file system location
    active: git
  cloud:
    config:
      server:
        #native:
          #search-location: "classpath:/config"
          #search-locations: "file:///F://Learn CS//Microservices//myMS//config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main #default branch to connect to
          timeout: 5
          clone-on-start: true
          force-pull: true

#encrypt:
 #key: an encryption key to encrypt and decrypt the properties.  we juts have to use POST localhost:8071/encrypt to encrypt value using plain text body and vice versa
 # to differentiate between normal value and encrypted value, add {cipher} before encrypted value. (springboot recommended)
server:
  port: 8071